# Generated by Django 4.0.1 on 2022-01-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location_row',
            field=models.CharField(choices=[('Row 1', 'Row 1'), ('Row 2', 'Row 2'), ('Row 3', 'Row 3')], default='Row 1', max_length=5),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location_slot',
            field=models.CharField(choices=[('Slot 1', 'Slot 1'), ('Slot 2', 'Slot 2'), ('Slot 3', 'Slot 3'), ('Slot 4', 'Slot 4'), ('Slot 5', 'Slot 5')], default='Slot 1', max_length=6),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='shelve',
            field=models.CharField(choices=[('Shelf 1', 'Shelf 1'), ('Shelf 2', 'Shelf 2'), ('Shelf 3', 'Shelf 3'), ('Shelf 4', 'Shelf 4'), ('Shelf 5', 'Shelf 5'), ('Shelf 6', 'Shelf 6'), ('Shelf 7', 'Shelf 7'), ('Shelf 8', 'Shelf 8'), ('Shelf 9', 'Shelf 9'), ('Shelf 10', 'Shelf 10'), ('Shelf 11', 'Shelf 11'), ('Shelf 12', 'Shelf 12'), ('Shelf 13', 'Shelf 13'), ('Shelf 14', 'Shelf 14'), ('Shelf 15', 'Shelf 15')], default='Shelf 1', max_length=12),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ware_house',
            field=models.CharField(choices=[('Ware House 1', 'Ware House 1'), ('Ware House 2', 'Ware House 2')], default='Ware House 1', max_length=12),
        ),
    ]
