# Generated by Django 4.0.1 on 2022-01-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_alter_inventory_location_row_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['inventory_id']},
        ),
    ]
